### ISSUE TITLE
Wenn ein User auf eine Katastrophe klickt soll er in der Katastrophen View eine TopTen Liste von gesuchten Objekte finden auf die mit einem Klick ein Angebot abgeben kann

### ISSUE THREAD

**Issue by LinusTU** [ExtremeEnvironment/edge-server#16]

**Comment by leolileo** [comment]
Ist diese Funktion wirklich erwünscht wegen Anonymität etc?

**Comment by LinusTU** [comment]
Sie sollen nur das ActionObject sehen nicht die Action, und dann ein Angebot(Aktion) mit diesem ActionObject erstellen können. Also dass wenn sie auf ein angezeigtes ActionObject drauf klicken sie weitergeleitet (oder pop-up mir egal) werden, wo sie dann das ActionObject vorausgewählt haben und nur noch ihren Standort angeben müssen, um das Angebot zu erstellen. mit "api/action-objects/topten/{id}" kriegst du die Zehn meist gesuchten ActionObjects in einer Liste zurück zu einer bestimmten Disaster-Id.
